### ISSUE TITLE
Possible to SetPosition with milliseconds?

### ISSUE THREAD

**Issue by knowpwr** [Zexuz/MPC-HC-CSharp-Api#5]
Hello. Is it possible to use the `SetPosition` with `TimeSpam` of milliseconds. Whenever I try the TimeSpan with days, hours, minutes, seconds, and milliseconds, the player is moved to the last position within the video. It only works properly if I use hours/minutes/seconds. 

Thanks for your time.

**Comment by Zexuz** [comment]
Im not sure I get what you are saying. You say it works properly when using a time-span set with hours/minutes/seconds but using days and milliseconds, it does not work, and the player skips to the last position of the video?

**Comment by Zexuz** [comment]
If that's the case, then passing in days might be a bug. Ofc the first criteria is to have a video longer then one day, otherwise you do skip to the end.

But when it comes to the millisecond question, I don't think that's possible. Take a look here

https://github.com/Zexuz/MPC-HC-CSharp-Api/blob/9d82310bacc5a116ab4c04f9dac6c0391536aaab/MPC-HC.Test/HtmlParserTest.cs#L34

By looking at this, it does seem like the API only supports HH:MM:SS when it comes to setting the position. So I guess this line here
https://github.com/Zexuz/MPC-HC-CSharp-Api/blob/9d82310bacc5a116ab4c04f9dac6c0391536aaab/MPC-HC.Domain/Services/CommandService.cs#L35 should only return a format of HH:MM:SS, and not the DD:HH:MM:SS:MS that it is currently.

If you do a PR, I can merge and update the NuGet package.

**Comment by knowpwr** [comment]
Thank you for the detailed explanation. It is much appreciated.
